### ISSUE TITLE
CommentString is error?!

### ISSUE THREAD

**Issue by blackmaple** [lukazh/ini-parser-standard#1]
I think 
CommentString  to
 list<string> Comment{get;}
 comments =>  ;  ' & more 

[xxx]
aa=aa 'x
key => aa
val  => aa
 but  now val => aa 'x

**Comment by lukazh** [comment]
Since there's no formal standard for INI file format, some features such as inline comment may not be supported(by default). You can customize the `IniParserConfiguration.CommentRegex` property to change the comment match behavior.
