### ISSUE TITLE
Project URL incorrect

### ISSUE THREAD

**Issue by DickBaker** [lukazh/ini-parser-standard#4]
The VS22 Preview **NuGet GUI** notes that the Project URL is **https://github.com/ravensorb/ini-parser** but this gives 404
- presumably this should be corrected to **https://github.com/lukazh/ini-parser-standard**

**Comment by lukazh** [comment]
I believe the package you were seeing should be "ini-parser-netcore", while the package for this repo is "IniFileParserStandard".
